const WARNING='Ferramenta de estudo. Não utilize durante a votação.';
const SLOTS=[['federal','Deputado federal'],['estadual','Deputado estadual'],['senador1','Senador · 1ª escolha'],['senador2','Senador · 2ª escolha'],['governador','Governador'],['presidente','Presidente']];
const $=id=>document.getElementById(id);
const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const office=slot=>slot.startsWith('senador')?'senador':slot;
const key=c=>`${c.office}-${c.number}`;
let candidates=[],selected={},snapshot=null,cardBlob=null;
try{localStorage.removeItem('memoriza-voto-2026')}catch{}
const widgets={};
function feedback(text){$('feedback').textContent=text}
function update(){const count=Object.keys(selected).length;$('progress').textContent=`${count} / ${SLOTS.length}`;$('generate').disabled=count!==SLOTS.length;snapshot=null;cardBlob=null;$('output').hidden=true;$('empty').hidden=false;feedback('')}
function avatar(c){if(c.photo){const img=document.createElement('img');img.className='avatar';img.alt='';img.src=c.photo;img.loading='lazy';img.addEventListener('error',()=>img.replaceWith(initials(c)),{once:true});return img}return initials(c)}
function initials(c){const span=document.createElement('span');span.className='avatar';span.textContent=c.name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('');span.title='Fotografia indisponível';return span}
function createField(slot,label,index){const root=document.createElement('div');root.className='field';const title=document.createElement('label');title.htmlFor=`input-${slot}`;title.textContent=label;const box=document.createElement('div');box.className='field-box';const input=document.createElement('input');input.id=title.htmlFor;input.placeholder='Digite o nome do candidato';input.autocomplete='off';input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-expanded','false');input.setAttribute('aria-controls',`list-${slot}`);const clear=document.createElement('button');clear.type='button';clear.className='clear';clear.textContent='×';clear.setAttribute('aria-label',`Limpar ${label}`);clear.hidden=true;const list=document.createElement('div');list.className='suggestions';list.id=`list-${slot}`;list.setAttribute('role','listbox');list.hidden=true;const detail=document.createElement('div');detail.className='selected-detail';detail.id=`detail-${slot}`;input.setAttribute('aria-describedby',detail.id);box.append(input,clear,list);root.append(title,box,detail);$('fields').append(root);let active=-1,matches=[];
const close=()=>{list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');active=-1};
const choose=c=>{selected[slot]=c;input.value=c.name;detail.textContent=`${c.number} · ${c.party} · ${c.state}`;clear.hidden=false;close();update();};
function search(){const q=normalize(input.value);list.replaceChildren();active=-1;matches=[];input.removeAttribute('aria-activedescendant');if(!q){close();return}const other=slot==='senador1'?'senador2':slot==='senador2'?'senador1':null;matches=candidates.filter(c=>c.office===office(slot)&&(normalize(c.name).includes(q)||c.number.startsWith(q))&&(!other||selected[other]?.number!==c.number)).sort((a,b)=>Number(normalize(b.name).startsWith(q))-Number(normalize(a.name).startsWith(q))||a.name.localeCompare(b.name,'pt-BR')).slice(0,20);list.hidden=false;input.setAttribute('aria-expanded','true');if(!matches.length){const p=document.createElement('div');p.className='no-match';p.textContent='Nenhum candidato encontrado nesta relação. Confira o nome e o cargo.';list.append(p)}matches.forEach((c,i)=>{const item=document.createElement('button');item.type='button';item.className='suggestion';item.setAttribute('role','option');item.setAttribute('aria-selected','false');item.id=`option-${index}-${i}`;item.tabIndex=-1;item.append(avatar(c));const info=document.createElement('span');info.className='candidate';const name=document.createElement('strong');name.textContent=c.name;const meta=document.createElement('small');meta.textContent=`${label} · ${c.party} · ${c.state}`;info.append(name,meta);const number=document.createElement('b');number.textContent=c.number;item.append(info,number);item.addEventListener('click',()=>choose(c));list.append(item)})}
input.addEventListener('input',()=>{delete selected[slot];detail.textContent='';clear.hidden=!input.value;update();search()});input.addEventListener('focus',()=>{if(!selected[slot])search()});clear.addEventListener('click',()=>{input.value='';detail.textContent='';clear.hidden=true;delete selected[slot];close();update();input.focus()});input.addEventListener('keydown',e=>{if(e.key==='Escape'){close();return}if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();if(list.hidden)search();if(matches.length){active=(active+(e.key==='ArrowDown'?1:-1)+matches.length)%matches.length;[...list.querySelectorAll('.suggestion')].forEach((b,i)=>{b.classList.toggle('active',i===active);b.setAttribute('aria-selected',String(i===active))});input.setAttribute('aria-activedescendant',`option-${index}-${active}`);list.children[active].scrollIntoView({block:'nearest'})}}if(e.key==='Enter'&&!list.hidden){e.preventDefault();if(active>=0)choose(matches[active])}});document.addEventListener('pointerdown',e=>{if(!root.contains(e.target))close()});widgets[slot]={choose,close,input};}
function round(ctx,x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function fit(ctx,text,maxWidth,start,min=15){let size=start;do{ctx.font=`700 ${size}px Arial`;if(ctx.measureText(text).width<=maxWidth)break;size--}while(size>min);return size}
async function loadPhoto(c){if(!c.photo)return null;return new Promise(resolve=>{const img=new Image();img.crossOrigin='anonymous';const timer=setTimeout(()=>resolve(null),3500);img.onload=()=>{clearTimeout(timer);resolve(img)};img.onerror=()=>{clearTimeout(timer);resolve(null)};img.src=c.photo})}
async function drawCard(rows){
 const canvas=$('card');canvas.width=1080;canvas.height=1030;
 const ctx=canvas.getContext('2d');const photos=await Promise.all(rows.map(r=>loadPhoto(r.candidate)));
 round(ctx,0,0,1080,1030,0,'#080f18');
 const header=ctx.createLinearGradient(0,0,1080,150);header.addColorStop(0,'#123930');header.addColorStop(1,'#182c47');round(ctx,0,0,1080,142,0,header);
 ctx.fillStyle='#8bffb2';ctx.font='700 18px Arial';ctx.fillText('MT 2026 · MEU CARTÃO DE ESTUDO',38,40);
 ctx.fillStyle='#f0fff7';ctx.font='700 43px Arial';ctx.fillText('MEMORIZE JÁ',38,95);
 ctx.fillStyle='#32e6df';ctx.fillRect(38,122,1004,2);
 rows.forEach((row,i)=>{
  const y=164+i*112,c=row.candidate,accent=['#8bffb2','#54e8f0','#c5a5ff'][i%3];
  round(ctx,28,y,1024,100,12,'#12202d');round(ctx,28,y,4,100,2,accent);
  round(ctx,45,y+10,68,80,8,'#213b40');
  if(photos[i]){ctx.save();ctx.beginPath();ctx.roundRect(45,y+10,68,80,8);ctx.clip();const img=photos[i],scale=Math.max(68/img.width,80/img.height);ctx.drawImage(img,45+(68-img.width*scale)/2,y+10+(80-img.height*scale)/2,img.width*scale,img.height*scale);ctx.restore()}
  else{ctx.fillStyle=accent;ctx.font='700 24px Arial';ctx.fillText(c.name.split(/\s+/).slice(0,2).map(w=>w[0]).join(''),54,y+57)}
  ctx.fillStyle=accent;ctx.font='700 15px Arial';ctx.fillText(row.label.toUpperCase(),136,y+24);
  ctx.fillStyle='#edf5f7';fit(ctx,c.name,560,27,15);ctx.fillText(c.name,136,y+56);
  ctx.fillStyle='#a7becb';ctx.font='16px Arial';ctx.fillText(c.party.length>65?c.party.slice(0,62)+'…':c.party,136,y+82);
  ctx.fillStyle=accent;ctx.textAlign='right';ctx.font='700 62px Arial';ctx.fillText(c.number,1023,y+65);ctx.textAlign='left';
 });
 round(ctx,28,853,1024,70,10,'#2b2719');ctx.fillStyle='#ffdf8a';ctx.font='700 23px Arial';ctx.fillText('Ferramenta de estudo. Não utilize durante a votação.',45,896);
 ctx.fillStyle='#a7becb';ctx.font='16px Arial';ctx.fillText('Dados: TRE-MT · 11/09/2026 | Presidência · 02/10/2026',38,952);
 ctx.fillText('Fotos: TSE · dadosabertos.tse.jus.br · Creative Commons Atribuição',38,978);
 ctx.fillText('Confira a situação atual da candidatura no TSE.',38,1004);
 $('card-description').textContent=rows.map(r=>`${r.label}: ${r.candidate.name}, ${r.candidate.number}`).join('. ')+'. '+WARNING+'. Fotos dos candidatos: TSE, Portal de Dados Abertos, Creative Commons Atribuição.';
 canvas.setAttribute('aria-describedby','card-description');
 return new Promise((resolve,reject)=>{try{canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Não foi possível gerar a imagem.')),'image/png')}catch(e){reject(e)}})
}
$('choices').addEventListener('submit',async e=>{e.preventDefault();if(SLOTS.some(([slot])=>!selected[slot]))return;if(selected.senador1.number===selected.senador2.number){feedback('Escolha duas pessoas diferentes para o Senado.');return}Object.values(widgets).forEach(w=>w.close());const rows=SLOTS.map(([slot,label])=>({label,candidate:{...selected[slot]}}));$('generate').disabled=true;$('generate').textContent='Gerando cartão…';try{const blob=await drawCard(rows);if(rows.some((r,i)=>key(r.candidate)!==(selected[SLOTS[i][0]]&&key(selected[SLOTS[i][0]]))))return;snapshot=rows;cardBlob=blob;$('empty').hidden=true;$('output').hidden=false;$('result-title').scrollIntoView({behavior:'smooth',block:'start'});feedback('Cartão pronto. Você pode copiar, compartilhar ou salvar.')}catch{feedback('Não foi possível gerar o cartão. Tente novamente.')}finally{$('generate').textContent='Gerar cartão ↗';$('generate').disabled=Object.keys(selected).length!==SLOTS.length}});
function textCard(){return ['MEMORIZE JÁ — MT 2026','',...snapshot.flatMap(r=>[`${r.label.toUpperCase()}`,`${r.candidate.name} — ${r.candidate.number}`,'']),WARNING,'','Fontes: TRE-MT (11/09/2026); Presidência (02/10/2026).','Fotos: TSE — Portal de Dados Abertos. Creative Commons Atribuição.','https://dadosabertos.tse.jus.br/pt_BR/dataset/candidatos-2026','Confira a situação atual no TSE: https://divulgacandcontas.tse.jus.br/'].join('\n')}
function download(){const url=URL.createObjectURL(cardBlob);const a=document.createElement('a');a.href=url;a.download='memorize-ja-2026.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
$('copy-text').addEventListener('click',async()=>{if(!snapshot)return;const text=textCard();try{await navigator.clipboard.writeText(text);feedback('Dados copiados. Cole no aplicativo de notas.')}catch{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.top='0';document.body.append(ta);ta.select();const ok=document.execCommand('copy');ta.remove();feedback(ok?'Dados copiados.':'O navegador bloqueou a cópia. Use Salvar para baixar o cartão.')}});
$('copy-image').addEventListener('click',async()=>{if(!cardBlob)return;try{if(!navigator.clipboard?.write||typeof ClipboardItem==='undefined')throw new Error();await navigator.clipboard.write([new ClipboardItem({'image/png':cardBlob})]);feedback('Imagem copiada. Cole em um aplicativo compatível.')}catch{download();feedback('Este navegador não permitiu copiar a imagem. O cartão foi enviado para download.')}});
$('share').addEventListener('click',async()=>{if(!cardBlob)return;const file=new File([cardBlob],'memorize-ja-2026.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})&&navigator.share){try{await navigator.share({files:[file],title:'Memorize Já',text:WARNING});feedback('Compartilhamento aberto. Escolha o WhatsApp no menu do aparelho.')}catch(e){if(e.name!=='AbortError'){download();feedback('O compartilhamento falhou. Anexe a imagem baixada no WhatsApp.')}}}else{download();feedback('Imagem enviada para download. Abra o WhatsApp e anexe memorize-ja-2026.png.')}});
$('save').addEventListener('click',async()=>{if(!cardBlob)return;if(window.showSaveFilePicker){try{const handle=await window.showSaveFilePicker({suggestedName:'memorize-ja-2026.png',types:[{description:'Imagem PNG',accept:{'image/png':['.png']}}]});const writer=await handle.createWritable();await writer.write(cardBlob);await writer.close();feedback('Cartão salvo na pasta escolhida.');return}catch(e){if(e.name==='AbortError')return}}download();feedback('Cartão enviado para download. A pasta depende das configurações do navegador.')});
$('edit').addEventListener('click',()=>{$('picker-title').scrollIntoView({behavior:'smooth'});widgets.federal.input.focus()});
SLOTS.forEach(([slot,label],index)=>createField(slot,label,index));
function resetChoices(){selected={};for(const [slot] of SLOTS){widgets[slot].input.value='';widgets[slot].close();$('detail-'+slot).textContent='';widgets[slot].input.closest('.field').querySelector('.clear').hidden=true}update()}
window.addEventListener('pageshow',resetChoices);
resetChoices();
try{const response=await fetch('./candidates.json?v=photos-20261003-all-presidents');if(!response.ok)throw new Error();const data=await response.json();candidates=data.candidates;$('load-status').textContent=`${candidates.length} registros de referência disponíveis. Busque por nome ou número.`;}catch{$('load-status').textContent='Não foi possível carregar os candidatos. Recarregue a página para tentar novamente.';Object.values(widgets).forEach(w=>w.input.disabled=true)}
